on:
  push:
    branches:
      - master
jobs:
  run_pull:
    name: run pull
    runs-on: ubuntu-latest
    steps:
    - name: install ssh keys
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: 139.59.133.32
        username: david
        key: ${{ secrets.SSH_PRIVATE_KEY}}
        port: ${{ secrets.PORT }}
        command_timeout: 30m
        script: | 
          echo "Nice Job!!!"