on:
  push:
    branches:
      - master
jobs:
  run_pull:
    name: run pull
    runs-on: ubuntu-latest
    steps:
    - name: install ssh keys
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{secrets.HOST}}
        key: ${{secrets.SSH_PRIVATE_KEY}}
        username: ${{secrets.USER}}
        script: |
          cd ~/droplet-deploy/
          git pull origin master
          echo "ok?"
